# Generated by Django 4.1.2 on 2022-11-23 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_osoba_miesiac_dodania_alter_osoba_imie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
